### PR TITLE
Limit customer access

### PR DESCRIPTION
**Pull request by ar45**
Limit customer access to admin or users that have access to mailbox with conversations of customer.

### CODE REVIEW

**Comment by freescout-help** [comment]
Thanks. This solution does not take one thing into account:

`IN` statement in DB usually has some limit on the number of items you can list in brackets, so if the `select` below returns more customers than `IN` in your DB allows you will get an error.

**Comment by ar45** [comment]
Hm. I tried using WHERE EXISTS but I got a laravel error perhaps due to using laravel 5.5

is the following query ok?

```php
$customers_query->where(function ($query) use ($user) {
                $query->whereRaw('EXISTS (
                    SELECT 1
                    FROM conversations JOIN mailbox_user ON conversations.mailbox_id = mailbox_user.mailbox_id
                    WHERE mailbox_user.user_id = ?
                    AND conversations.customer_id = customers.id
                    LIMIT 1
                )', [$user->id]);
            });
```

**Comment by freescout-help** [comment]
It has been adjusted and added as a single commit: https://github.com/freescout-help-desk/freescout/commit/9a6429ea9761b4e758a9f654165122eeef453613

Thanks for the contribution.

**Comment by freescout-help** [comment]
Instructions:
https://github.com/freescout-help-desk/freescout/wiki/FAQ#is-it-possible-to-have-separate-contactscustomers-per-mailbox

**Comment by freescout-help** [comment]
It should be fixed now.

**Comment by ar45** [comment]
Works as expected. Thank you very much!

**Pull request closed without merging**
